from django.db import models
from common.models import ActiveStatusMixin


# Create your models here.
class Equipment(ActiveStatusMixin, models.Model):

    class EquipmentType(models.TextChoices):
        CAMERA = 'camera', 'Camera'
        LENS = 'lens', 'Lens'
        DRONE = 'drone', 'Drone'
        LIGHTING = 'lighting', 'Lighting'
        OTHER = 'other', 'Other'

    brand = models.CharField(
        max_length=100,
    )

    model = models.CharField(
        max_length=100,
    )

    equipment_type = models.CharField(
        max_length=50,
        choices=EquipmentType,
        default=EquipmentType.OTHER,
    )

    specifications = models.TextField(
        blank=True,
    )

    internal_id = models.CharField(
        max_length=50,
        unique=True,
        help_text='Internal inventory ID (generated by the studio).',
    )

    purchase_date = models.DateField(
        blank=True,
        null=True,
    )

    notes = models.TextField(
        blank=True,
    )

    productions = models.ManyToManyField(
        'productions.Production',
        related_name='equipment',
        blank=True,
    )

    class Meta:
        ordering = ['brand', 'model', 'internal_id']
        verbose_name_plural = 'Equipment'

    def __str__(self):
        return f'{self.brand} {self.model} ({self.get_equipment_type_display()})'
