# Generated by Django 6.0.3 on 2026-03-07 12:46

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_seed_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='equipment_covers/'),
        ),
    ]
