# Generated by Django 6.0.3 on 2026-03-07 12:46

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0005_seed_productions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='category_covers/', verbose_name='Category image'),
        ),
        migrations.AlterField(
            model_name='production',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='production_covers/', verbose_name='Production image'),
        ),
    ]
